### ISSUE TITLE
跨网通信问题

### ISSUE THREAD

**Issue by Sunner-Chao** [wang1xiang/webrtc-tutorial#1]
author你好，我想请教个问题，我成功将该项目部署至云服务器中，同时https的ssl证书配置也是ok的，两台设备只能处在同一个局域网中访问公网云服务器IP才能互相通信。是什么原因导致的呢?
![111](https://github.com/wang1xiang/webrtc-tutorial/assets/102290983/197d53a7-360b-4aae-97a5-36bfa16faff5)
![222](https://github.com/wang1xiang/webrtc-tutorial/assets/102290983/8193c3e0-9b58-4afa-94d3-065c97af3a30)
![333](https://github.com/wang1xiang/webrtc-tutorial/assets/102290983/83216d88-3676-4384-9937-3562a5729c3a)

**Comment by Sunner-Chao** [comment]
好像有头绪了，应该是stun/turn配置吧？

**Comment by wang1xiang** [comment]
> 好像有头绪了，应该是stun/turn配置吧？

是的，需要配置stun服务
